  order.inc : Lokale Setzungen fuer den Betrieb von ORDER
  2007-10-29  Wird von  o-init.flx  einbezogen
     Diese Datei modifizieren und ins eigene Datenverz. speichern
     Dann neu starten

  Textvorlage fuer Bestellungen
$Best bestell.rtf

  Nummernvergabe (s.  h nummer )

  Signaturen-Generator:
$Sgen SSTD
  Zugangsnummern-Generator:
$Zgen ZSTD

  Waehrungstabelle (Code des Systemsatzes) Default: WHRG
$Wtab WHRG

  Name des Systems (dann  h order  statt  h orda)
#uoZ order
